version: 0.2

phases:
  pre_build:
    commands:
      - echo "Hello from my pipeline"
      - pip install pipenv
  build:
    commands:
      - echo "Installing dependencies"
      - pip install flask
      - echo "Testing"
      - python -m unittest 
  post_build:
    commands:
      - echo Build completed on `date`
